version: 2
before:
  hooks:
    - go mod tidy
builds:
  - id: cli
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
      - dragonfly
      - freebsd
      - netbsd
      - openbsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: freebsd
        goarch: arm64
      - goos: windows
        goarch: arm
universal_binaries:
  - id: cli
    replace: false
archives:
  - id: cli
    format_overrides:
      - goos: windows
        formats: ["zip"]
    files:
      - README.md
      - COPYING
    name_template: >-
      {{- .ProjectName -}}_
      {{- .Version -}}_
      {{- if eq .Os "darwin" -}}
      macos
      {{- else -}}
      {{ .Os }}
      {{- end -}}_
      {{- .Arch -}}
checksum:
  name_template: checksums.txt
snapshot:
  version_template: "{{ .Env.VERSION }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
